allowBuilds:
  esbuild: true
  workerd: true
autoInstallPeers: false
minimumReleaseAge: 0

overrides:
  brace-expansion@<1.1.16: 1.1.16
  brace-expansion@>=2.0.0 <2.1.2: 2.1.2
  brace-expansion@>=3.0.0 <5.0.8: 5.0.8
  postcss: 8.5.25
  sharp: 0.35.3
